"""add detection rule id to alerts

Revision ID: 0095cb51a35d
Revises: a6cf4ba02c3a
Create Date: 2026-08-16 15:15:31.007878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0095cb51a35d'
down_revision: Union[str, Sequence[str], None] = 'a6cf4ba02c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('detection_rule_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_alerts_detection_rule_id'), 'alerts', ['detection_rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_detection_rule_id'), table_name='alerts')
    op.drop_column('alerts', 'detection_rule_id')
    # ### end Alembic commands ###
