"""Add alert analyst assignment

Revision ID: 7569ef061300
Revises: eea5adb9d01c
Create Date: 2026-08-15 18:32:18.839300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7569ef061300'
down_revision: Union[str, Sequence[str], None] = 'eea5adb9d01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('assigned_analyst', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'assigned_analyst')
    # ### end Alembic commands ###
