"""create threat indicators

Revision ID: 8641d2165e62
Revises: 0095cb51a35d
Create Date: 2026-08-16 16:10:27.830160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8641d2165e62'
down_revision: Union[str, Sequence[str], None] = '0095cb51a35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_indicators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('indicator_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('reputation', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_type', 'value', name='uq_threat_indicators_type_value')
    )
    op.create_index(op.f('ix_threat_indicators_indicator_type'), 'threat_indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_threat_indicators_reputation'), 'threat_indicators', ['reputation'], unique=False)
    op.create_index(op.f('ix_threat_indicators_source'), 'threat_indicators', ['source'], unique=False)
    op.create_index(op.f('ix_threat_indicators_value'), 'threat_indicators', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_indicators_value'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_source'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_reputation'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_indicator_type'), table_name='threat_indicators')
    op.drop_table('threat_indicators')
    # ### end Alembic commands ###
