"""Add security events

Revision ID: 940cff539727
Revises: 06612ab28a83
Create Date: 2026-08-15 23:06:36.681967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940cff539727'
down_revision: Union[str, Sequence[str], None] = '06612ab28a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('process_name', sa.String(length=255), nullable=True),
    sa.Column('command_line', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_event_time'), 'security_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_hostname'), 'security_events', ['hostname'], unique=False)
    op.create_index(op.f('ix_security_events_source'), 'security_events', ['source'], unique=False)
    op.create_index(op.f('ix_security_events_source_ip'), 'security_events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_security_events_username'), 'security_events', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_username'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_source_ip'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_source'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_hostname'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_time'), table_name='security_events')
    op.drop_table('security_events')
    # ### end Alembic commands ###
