"""Link alerts to security events

Revision ID: a6cf4ba02c3a
Revises: 940cff539727
Create Date: 2026-08-15 23:32:04.395105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6cf4ba02c3a'
down_revision: Union[str, Sequence[str], None] = '940cff539727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('source_event_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_alerts_source_event_id'), 'alerts', ['source_event_id'], unique=False)
    op.create_foreign_key('fk_alerts_source_event_id_security_events', 'alerts', 'security_events', ['source_event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_alerts_source_event_id_security_events', 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_source_event_id'), table_name='alerts')
    op.drop_column('alerts', 'source_event_id')
    # ### end Alembic commands ###
