"""add security audit events

Revision ID: e6ab1b3d315d
Revises: 4748431cbcbf
Create Date: 2026-08-19 19:20:48.406002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6ab1b3d315d'
down_revision: Union[str, Sequence[str], None] = '4748431cbcbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('identity_hash', sa.String(length=64), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('success', 'failure', 'denied', 'throttled')", name='ck_security_audit_events_outcome'),
    sa.CheckConstraint("severity IN ('info', 'warning', 'high')", name='ck_security_audit_events_severity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_events_created_at'), 'security_audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_audit_events_event_type'), 'security_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_events_identity_hash'), 'security_audit_events', ['identity_hash'], unique=False)
    op.create_index(op.f('ix_security_audit_events_outcome'), 'security_audit_events', ['outcome'], unique=False)
    op.create_index(op.f('ix_security_audit_events_severity'), 'security_audit_events', ['severity'], unique=False)
    op.create_index(op.f('ix_security_audit_events_user_id'), 'security_audit_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_audit_events_user_id'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_severity'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_outcome'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_identity_hash'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_event_type'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_created_at'), table_name='security_audit_events')
    op.drop_table('security_audit_events')
    # ### end Alembic commands ###
